import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ScrollContextProvider } from "@/contexts/ScrollContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;1,900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Protest+Guerrilla&display=swap"
          rel="stylesheet"
        ></link>
        {/*  */}
        <link
          href="https://fonts.googleapis.com/css2?family=Arvo:wght@700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className} style={{ height: 3000 }}>
        <ScrollContextProvider>{children}</ScrollContextProvider>
      </body>
    </html>
  );
}
